export const LOAD_DEPARTMENT_LIST='LOAD_DEPARTMENT_LIST';

export const LOAD_ADMIN='LOAD_ADMIN';

export const LOAD_STAFF='LOAD_STAFF';

export const LOAD_STAFF_DETAILS='LOAD_STAFF_DETAILS';

export const LOAD_VISITOR_LIST='LOAD_VISITOR_LIST';

export const CHANGE_SEARCH_FIELD='CHANGE_SEARCH_FIELD';

export const LOAD_STAFF_LIST='LOAD_STAFF_LIST';
